-- 코드를 입력하세요
SELECT BOOK.BOOK_ID as BOOK_ID, AUTHOR.AUTHOR_NAME as AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK 
INNER JOIN AUTHOR WHERE BOOK.CATEGORY = '경제' AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID 
ORDER BY BOOK.PUBLISHED_DATE ASC;