-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, c.REPLY_ID, c.WRITER_ID, c.CONTENTS, 
DATE_FORMAT(c.CREATED_DATE, '%Y-%m-%d') FROM USED_GOODS_BOARD b INNER JOIN USED_GOODS_REPLY c 
ON b.BOARD_ID = c.BOARD_ID WHERE b.CREATED_DATE LIKE '2022-10%' ORDER BY 
c.CREATED_DATE ASC, b.TITLE ASC;